// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EditorController from "./editor_controller"
application.register("editor", EditorController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MarkdownViewerController from "./markdown_viewer_controller"
application.register("markdown-viewer", MarkdownViewerController)

import OnboardingStep1SelectController from "./onboarding_step_1_select_controller"
application.register("onboarding-step-1-select", OnboardingStep1SelectController)
