// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import EditorController from "./editor_controller"
application.register("editor", EditorController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import MarkdownViewerController from "./markdown_viewer_controller"
application.register("markdown-viewer", MarkdownViewerController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)
